### ISSUE TITLE
複数のグラフを色違いの線で描画する

### ISSUE THREAD

**Issue by nbeat** [nbeat/temp-humid-prototype#1]
複数のグラフを色違いの線で描画したいので、Kii の別バケツに、今取得している値の +1、-1度したデータをつっこんでみますね。

**Comment by AkiraSakai** [comment]
Temp2、Temp3 というバケツを作成して、データを入れ始めました。

**Comment by nbeat** [comment]
別々のバケツにデータ入れちゃうと別々の検索クエリになっちゃって、データ取得後のコールバック処理も別々になっちゃうからむずかしいなあ。
データオブジェクトにtemp1、temp2、temp3とIDみたいなのを振って、おんなじバケツに入ってれば今の設計のままで行けそうだけど。

**Comment by nbeat** [comment]
10分間分のデータを取得してグラフを表示する処理を実装した。
